# Configuration scss-lint for Gizra.com.

scss_files: "app/_scss/*.scss"

linters:
  ColorKeyword:
    enabled: false

  ColorVariable:
    enabled: false

  HexLength:
      enabled: false

  HexNotation:
      enabled: false

  IdSelector:
      enabled: false

  LeadingZero:
    enabled: false

  NestingDepth:
    max_depth: 6

  PropertySortOrder:
    enabled: false

  SelectorDepth:
    max_depth: 5
